apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dmp-ekstern
  namespace: nada
  labels:
    team: nada
spec:
  image: ghcr.io/navikt/nada/test-image:v20
  port: 8080
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 70
  env:
    - name: CERT_PATH
      value: "/etc/pki/tls/cacert.pem"
    - name: HOST
      value: storage.googleapis.com
  ingresses:
    - https://nada.ekstern.dev.nav.no
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - host: cdn.nav.no
        - host: data.nav.no
