apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: datafortelling-proxy
  namespace: nada
  labels:
    team: nada
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 70
  env:
    - name: HOST
      value: storage.googleapis.com
    - name: BUCKET
      value: {{bucket}}
  ingresses:
  {{#each ingress}}
    - {{.}}
  {{/each}}
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
